version: "1.0"

stages:
  - Clone
  - Build
  - Release

steps:
  main_clone:
    title: Cloning repository
    stage: Clone
    type: git-clone
    arguments:
      repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
      revision: ${{CF_BRANCH}}
      git: codefresh-github-app
      depth: 1

  build:
    title: Compiling
    stage: Build
    arguments:
      image: denoland/deno:alpine-1.39.1
      commands:
        - cf_export VERSION=$(cat VERSION)
        - deno task compile

  github_release:
    title: Publishing release
    stage: Release
    type: github-release
    arguments:
      git_context_name: codefresh-github-app
      release_name: '${{VERSION}}'
      release_description: ${{CF_COMMIT_MESSAGE}}
      release_tag: ${{VERSION}}
      files:
        - '${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/bin/cf-transfer_linux_x86_64'
        - '${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/bin/cf-transfer_windows_x86_64.exe'
        - '${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/bin/cf-transfer_darwin_x86_64'
        - '${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/bin/cf-transfer_darwin_arm64'